package com.yy.yec.ui.widget;

import android.support.annotation.DrawableRes;
import android.support.annotation.IdRes;
import android.util.ArrayMap;

import com.common.widget.comment.brow.BrowEntity;
import com.common.widget.comment.brow.BrowType;
import com.yy.yec.R;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created by zzq on 2016/10/3.
 */
public enum BrowRules {
    KJEMOJI0(BrowType.QQ, R.mipmap.smiley_0, "[微笑]", "[0]"),
    KJEMOJI1(BrowType.QQ, R.mipmap.smiley_1, "[撇嘴]", "[1]"),
    KJEMOJI2(BrowType.QQ, R.mipmap.smiley_2, "[色]", "[2]"),
    KJEMOJI3(BrowType.QQ, R.mipmap.smiley_3, "[发呆]", "[3]"),
    KJEMOJI4(BrowType.QQ, R.mipmap.smiley_4, "[得意]", "[4]"),
    KJEMOJI5(BrowType.QQ, R.mipmap.smiley_5, "[流泪]", "[5]"),
    KJEMOJI6(BrowType.QQ, R.mipmap.smiley_6, "[害羞]", "[6]"),
    KJEMOJI7(BrowType.QQ, R.mipmap.smiley_7, "[闭嘴]", "[7]"),
    KJEMOJI8(BrowType.QQ, R.mipmap.smiley_8, "[睡]", "[8]"),
    KJEMOJI9(BrowType.QQ, R.mipmap.smiley_9, "[大哭]", "[9]"),
    KJEMOJI10(BrowType.QQ, R.mipmap.smiley_10, "[尴尬]", "[10]"),
    KJEMOJI11(BrowType.QQ, R.mipmap.smiley_11, "[发怒]", "[11]"),
    KJEMOJI12(BrowType.QQ, R.mipmap.smiley_12, "[调皮]", "[12]"),
    KJEMOJI13(BrowType.QQ, R.mipmap.smiley_13, "[呲牙]", "[13]"),
    KJEMOJI14(BrowType.QQ, R.mipmap.smiley_14, "[惊讶]", "[14]"),
    KJEMOJI15(BrowType.QQ, R.mipmap.smiley_15, "[难过]", "[15]"),
    KJEMOJI16(BrowType.QQ, R.mipmap.smiley_16, "[酷]", "[16]"),
    KJEMOJI17(BrowType.QQ, R.mipmap.smiley_17, "[冷汗]", "[17]"),
    KJEMOJI18(BrowType.QQ, R.mipmap.smiley_18, "[抓狂]", "[18]"),
    KJEMOJI19(BrowType.QQ, R.mipmap.smiley_19, "[吐]", "[19]"),
    KJEMOJI20(BrowType.QQ, R.mipmap.smiley_20, "[偷笑]", "[20]"),
    KJEMOJI21(BrowType.QQ, R.mipmap.smiley_21, "[可爱]", "[21]"),
    KJEMOJI22(BrowType.QQ, R.mipmap.smiley_22, "[白眼]", "[22]"),
    KJEMOJI23(BrowType.QQ, R.mipmap.smiley_23, "[傲慢]", "[23]"),
    KJEMOJI24(BrowType.QQ, R.mipmap.smiley_24, "[饥饿]", "[24]"),
    KJEMOJI25(BrowType.QQ, R.mipmap.smiley_25, "[困]", "[25]"),
    KJEMOJI26(BrowType.QQ, R.mipmap.smiley_26, "[惊恐]", "[26]"),
    KJEMOJI27(BrowType.QQ, R.mipmap.smiley_27, "[流汗]", "[27]"),
    KJEMOJI28(BrowType.QQ, R.mipmap.smiley_28, "[憨笑]", "[28]"),
    KJEMOJI29(BrowType.QQ, R.mipmap.smiley_29, "[大兵]", "[29]"),
    KJEMOJI30(BrowType.QQ, R.mipmap.smiley_30, "[奋斗]", "[30]"),
    KJEMOJI31(BrowType.QQ, R.mipmap.smiley_31, "[咒骂]", "[31]"),
    KJEMOJI32(BrowType.QQ, R.mipmap.smiley_32, "[疑问]", "[32]"),
    KJEMOJI33(BrowType.QQ, R.mipmap.smiley_33, "[嘘]", "[33]"),
    KJEMOJI34(BrowType.QQ, R.mipmap.smiley_34, "[晕]", "[34]"),
    KJEMOJI35(BrowType.QQ, R.mipmap.smiley_35, "[折磨]", "[35]"),
    KJEMOJI36(BrowType.QQ, R.mipmap.smiley_36, "[衰]", "[36]"),
    KJEMOJI37(BrowType.QQ, R.mipmap.smiley_37, "[骷髅]", "[37]"),
    KJEMOJI38(BrowType.QQ, R.mipmap.smiley_38, "[敲打]", "[38]"),
    KJEMOJI39(BrowType.QQ, R.mipmap.smiley_39, "[再见]", "[39]"),
    KJEMOJI40(BrowType.QQ, R.mipmap.smiley_40, "[擦汗]", "[40]"),
    KJEMOJI41(BrowType.QQ, R.mipmap.smiley_41, "[抠鼻]", "[41]"),
    KJEMOJI42(BrowType.QQ, R.mipmap.smiley_42, "[鼓掌]", "[42]"),
    KJEMOJI43(BrowType.QQ, R.mipmap.smiley_43, "[糗大了]", "[43]"),
    KJEMOJI44(BrowType.QQ, R.mipmap.smiley_44, "[坏笑]", "[44]"),
    KJEMOJI45(BrowType.QQ, R.mipmap.smiley_45, "[左哼哼]", "[45]"),
    KJEMOJI46(BrowType.QQ, R.mipmap.smiley_46, "[右哼哼]", "[46]"),
    KJEMOJI47(BrowType.QQ, R.mipmap.smiley_47, "[哈欠]", "[47]"),
    KJEMOJI48(BrowType.QQ, R.mipmap.smiley_48, "[鄙视]", "[48]"),
    KJEMOJI49(BrowType.QQ, R.mipmap.smiley_49, "[委屈]", "[49]"),
    KJEMOJI50(BrowType.QQ, R.mipmap.smiley_50, "[快哭了]", "[50]"),
    KJEMOJI51(BrowType.QQ, R.mipmap.smiley_51, "[阴险]", "[51]"),
    KJEMOJI52(BrowType.QQ, R.mipmap.smiley_52, "[亲亲]", "[52]"),
    KJEMOJI53(BrowType.QQ, R.mipmap.smiley_53, "[吓]", "[53]"),
    KJEMOJI54(BrowType.QQ, R.mipmap.smiley_54, "[可怜]", "[54]"),
    KJEMOJI55(BrowType.QQ, R.mipmap.smiley_55, "[菜刀]", "[55]"),
    KJEMOJI56(BrowType.QQ, R.mipmap.smiley_56, "[西瓜]", "[56]"),
    KJEMOJI57(BrowType.QQ, R.mipmap.smiley_57, "[啤酒]", "[57]"),
    KJEMOJI58(BrowType.QQ, R.mipmap.smiley_58, "[篮球]", "[58]"),
    KJEMOJI59(BrowType.QQ, R.mipmap.smiley_59, "[乒乓]", "[59]"),
    KJEMOJI60(BrowType.QQ, R.mipmap.smiley_60, "[咖啡]", "[60]"),
    KJEMOJI61(BrowType.QQ, R.mipmap.smiley_61, "[饭]", "[61]"),
    KJEMOJI62(BrowType.QQ, R.mipmap.smiley_62, "[猪头]", "[62]"),
    KJEMOJI63(BrowType.QQ, R.mipmap.smiley_63, "[玫瑰]", "[63]"),
    KJEMOJI64(BrowType.QQ, R.mipmap.smiley_64, "[凋谢]", "[64]"),
    KJEMOJI65(BrowType.QQ, R.mipmap.smiley_65, "[嘴唇]", "[65]"),
    KJEMOJI66(BrowType.QQ, R.mipmap.smiley_66, "[爱心]", "[66]"),
    KJEMOJI67(BrowType.QQ, R.mipmap.smiley_67, "[心碎]", "[67]"),
    KJEMOJI68(BrowType.QQ, R.mipmap.smiley_68, "[蛋糕]", "[68]"),
    KJEMOJI69(BrowType.QQ, R.mipmap.smiley_69, "[闪电]", "[69]"),
    KJEMOJI70(BrowType.QQ, R.mipmap.smiley_70, "[炸弹]", "[70]"),
    KJEMOJI71(BrowType.QQ, R.mipmap.smiley_71, "[刀]", "[71]"),
    KJEMOJI72(BrowType.QQ, R.mipmap.smiley_72, "[足球]", "[72]"),
    KJEMOJI73(BrowType.QQ, R.mipmap.smiley_73, "[瓢虫]", "[73]"),
    KJEMOJI74(BrowType.QQ, R.mipmap.smiley_74, "[便便]", "[74]"),
    KJEMOJI75(BrowType.QQ, R.mipmap.smiley_75, "[月亮]", "[75]"),
    KJEMOJI76(BrowType.QQ, R.mipmap.smiley_76, "[太阳]", "[76]"),
    KJEMOJI77(BrowType.QQ, R.mipmap.smiley_77, "[礼物]", "[77]"),
    KJEMOJI78(BrowType.QQ, R.mipmap.smiley_78, "[拥抱]", "[78]"),
    KJEMOJI79(BrowType.QQ, R.mipmap.smiley_79, "[强]", "[79]"),
    KJEMOJI80(BrowType.QQ, R.mipmap.smiley_80, "[弱]", "[80]"),
    KJEMOJI81(BrowType.QQ, R.mipmap.smiley_81, "[握手]", "[81]"),
    KJEMOJI82(BrowType.QQ, R.mipmap.smiley_82, "[胜利]", "[82]"),
    KJEMOJI83(BrowType.QQ, R.mipmap.smiley_83, "[抱拳]", "[83]"),
    KJEMOJI84(BrowType.QQ, R.mipmap.smiley_84, "[勾引]", "[84]"),
    KJEMOJI85(BrowType.QQ, R.mipmap.smiley_85, "[拳头]", "[85]"),
    KJEMOJI86(BrowType.QQ, R.mipmap.smiley_86, "[差劲]", "[86]"),
    KJEMOJI87(BrowType.QQ, R.mipmap.smiley_87, "[爱你]", "[87]"),
    KJEMOJI88(BrowType.QQ, R.mipmap.smiley_88, "[NO]", "[88]"),
    KJEMOJI89(BrowType.QQ, R.mipmap.smiley_89, "[OK]", "[89]"),
    KJEMOJI90(BrowType.QQ, R.mipmap.smiley_90, "[爱情]", "[90]"),
    KJEMOJI91(BrowType.QQ, R.mipmap.smiley_91, "[飞吻]", "[91]"),
    KJEMOJI92(BrowType.QQ, R.mipmap.smiley_92, "[跳跳]", "[92]"),
    KJEMOJI93(BrowType.QQ, R.mipmap.smiley_93, "[发抖]", "[93]"),
    KJEMOJI94(BrowType.QQ, R.mipmap.smiley_94, "[怄火]", "[94]"),
    KJEMOJI95(BrowType.QQ, R.mipmap.smiley_95, "[转圈]", "[95]"),
    KJEMOJI96(BrowType.QQ, R.mipmap.smiley_96, "[磕头]", "[96]"),
    KJEMOJI97(BrowType.QQ, R.mipmap.smiley_97, "[回头]", "[97]"),
    KJEMOJI98(BrowType.QQ, R.mipmap.smiley_98, "[跳绳]", "[98]"),
    KJEMOJI99(BrowType.QQ, R.mipmap.smiley_99, "[投降]", "[99]"),
    KJEMOJI100(BrowType.QQ, R.mipmap.smiley_100, "[激动]", "[100]"),
    KJEMOJI101(BrowType.QQ, R.mipmap.smiley_101, "[乱舞]", "[101]"),
    KJEMOJI102(BrowType.QQ, R.mipmap.smiley_102, "[献吻]", "[102]"),
    KJEMOJI103(BrowType.QQ, R.mipmap.smiley_103, "[左太极]", "[103]"),
    KJEMOJI104(BrowType.QQ, R.mipmap.smiley_104, "[右太极]", "[104]"),

    GITHUB0(BrowType.E, R.mipmap.bowtie, ":bowtie:", ":bowtie:"),
    GITHUB1(BrowType.E, R.mipmap.smile, ":smile:", ":smile:"),
    GITHUB2(BrowType.E, R.mipmap.laughing, ":laughing:", ":laughing:"),
    GITHUB3(BrowType.E, R.mipmap.blush, ":blush:", ":blush:"),
    GITHUB4(BrowType.E, R.mipmap.smiley, ":smiley:", ":smiley:"),
    GITHUB5(BrowType.E, R.mipmap.relaxed, ":relaxed:", ":relaxed:"),
    GITHUB6(BrowType.E, R.mipmap.smirk, ":smirk:", ":smirk:"),
    GITHUB7(BrowType.E, R.mipmap.heart_eyes, ":heart_eyes:", ":heart_eyes:"),
    GITHUB8(BrowType.E, R.mipmap.kissing_heart, ":kissing_heart:", ":kissing_heart:"),
    GITHUB9(BrowType.E, R.mipmap.kissing_closed_eyes, ":kissing_closed_eyes:", ":kissing_closed_eyes:"),
    GITHUB10(BrowType.E, R.mipmap.flushed, ":flushed:", ":flushed:"),
    GITHUB11(BrowType.E, R.mipmap.relieved, ":relieved:", ":relieved:"),
    GITHUB12(BrowType.E, R.mipmap.satisfied, ":satisfied:", ":satisfied:"),
    GITHUB13(BrowType.E, R.mipmap.grin, ":grin:", ":grin:"),
    GITHUB14(BrowType.E, R.mipmap.wink, ":wink:", ":wink:"),
    GITHUB15(BrowType.E, R.mipmap.stuck_out_tongue_winking_eye, ":stuck_out_tongue_winking_eye:", ":stuck_out_tongue_winking_eye:"),
    GITHUB16(BrowType.E, R.mipmap.stuck_out_tongue_closed_eyes, ":stuck_out_tongue_closed_eyes:", ":stuck_out_tongue_closed_eyes:"),
    GITHUB17(BrowType.E, R.mipmap.grinning, ":grinning:", ":grinning:"),
    GITHUB18(BrowType.E, R.mipmap.kissing, ":kissing:", ":kissing:"),
    GITHUB19(BrowType.E, R.mipmap.kissing_smiling_eyes, ":kissing_smiling_eyes:", ":kissing_smiling_eyes:"),
    GITHUB20(BrowType.E, R.mipmap.stuck_out_tongue, ":stuck_out_tongue:", ":stuck_out_tongue:"),
    GITHUB21(BrowType.E, R.mipmap.sleeping, ":sleeping:", ":sleeping:"),
    GITHUB22(BrowType.E, R.mipmap.worried, ":worried:", ":worried:"),
    GITHUB23(BrowType.E, R.mipmap.frowning, ":frowning:", ":frowning:"),
    GITHUB24(BrowType.E, R.mipmap.anguished, ":anguished:", ":anguished:"),
    GITHUB25(BrowType.E, R.mipmap.open_mouth, ":open_mouth:", ":open_mouth:"),
    GITHUB26(BrowType.E, R.mipmap.grimacing, ":grimacing:", ":grimacing:"),
    GITHUB27(BrowType.E, R.mipmap.confused, ":confused:", ":confused:"),
    GITHUB28(BrowType.E, R.mipmap.hushed, ":hushed:", ":hushed:"),
    GITHUB29(BrowType.E, R.mipmap.expressionless, ":expressionless:", ":expressionless:"),
    GITHUB30(BrowType.E, R.mipmap.unamused, ":unamused:", ":unamused:"),
    GITHUB31(BrowType.E, R.mipmap.sweat_smile, ":sweat_smile:", ":sweat_smile:"),
    GITHUB32(BrowType.E, R.mipmap.sweat, ":sweat:", ":sweat:"),
    GITHUB33(BrowType.E, R.mipmap.disappointed_relieved, ":disappointed_relieved:", ":disappointed_relieved:"),
    GITHUB34(BrowType.E, R.mipmap.weary, ":weary:", ":weary:"),
    GITHUB35(BrowType.E, R.mipmap.pensive, ":pensive:", ":pensive:"),
    GITHUB36(BrowType.E, R.mipmap.disappointed, ":disappointed:", ":disappointed:"),
    GITHUB37(BrowType.E, R.mipmap.confounded, ":confounded:", ":confounded:"),
    GITHUB38(BrowType.E, R.mipmap.fearful, ":fearful:", ":fearful:"),
    GITHUB39(BrowType.E, R.mipmap.cold_sweat, ":cold_sweat:", ":cold_sweat:"),
    GITHUB40(BrowType.E, R.mipmap.persevere, ":persevere:", ":persevere:"),
    GITHUB41(BrowType.E, R.mipmap.cry, ":cry:", ":cry:"),
    GITHUB42(BrowType.E, R.mipmap.sob, ":sob:", ":sob:"),
    GITHUB43(BrowType.E, R.mipmap.joy, ":joy:", ":joy:"),
    GITHUB44(BrowType.E, R.mipmap.astonished, ":astonished:", ":astonished:"),
    GITHUB45(BrowType.E, R.mipmap.scream, ":scream:", ":scream:"),
    GITHUB46(BrowType.E, R.mipmap.neckbeard, ":neckbeard:", ":neckbeard:"),
    GITHUB47(BrowType.E, R.mipmap.tired_face, ":tired_face:", ":tired_face:"),
    GITHUB48(BrowType.E, R.mipmap.angry, ":angry:", ":angry:"),
    GITHUB49(BrowType.E, R.mipmap.rage, ":rage:", ":rage:"),
    GITHUB50(BrowType.E, R.mipmap.triumph, ":triumph:", ":triumph:"),
    GITHUB51(BrowType.E, R.mipmap.sleepy, ":sleepy:", ":sleepy:"),
    GITHUB52(BrowType.E, R.mipmap.yum, ":yum:", ":yum:"),
    GITHUB53(BrowType.E, R.mipmap.mask, ":mask:", ":mask:"),
    GITHUB54(BrowType.E, R.mipmap.sunglasses, ":sunglasses:", ":sunglasses:"),
    GITHUB55(BrowType.E, R.mipmap.dizzy_face, ":dizzy_face:", ":dizzy_face:"),
    GITHUB56(BrowType.E, R.mipmap.imp, ":imp:", ":imp:"),
    GITHUB57(BrowType.E, R.mipmap.smiling_imp, ":smiling_imp:", ":smiling_imp:"),
    GITHUB58(BrowType.E, R.mipmap.neutral_face, ":neutral_face:", ":neutral_face:"),
    GITHUB59(BrowType.E, R.mipmap.no_mouth, ":no_mouth:", ":no_mouth:"),
    GITHUB60(BrowType.E, R.mipmap.innocent, ":innocent:", ":innocent:"),
    GITHUB61(BrowType.E, R.mipmap.alien, ":alien:", ":alien:"),
    GITHUB62(BrowType.E, R.mipmap.yellow_heart, ":yellow_heart:", ":yellow_heart:"),
    GITHUB63(BrowType.E, R.mipmap.blue_heart, ":blue_heart:", ":blue_heart:"),
    GITHUB64(BrowType.E, R.mipmap.purple_heart, ":purple_heart:", ":purple_hert:"),
    GITHUB65(BrowType.E, R.mipmap.heart, ":heart:", ":heart:"),
    GITHUB66(BrowType.E, R.mipmap.green_heart, ":green_heart:", ":green_heart:"),
    GITHUB67(BrowType.E, R.mipmap.broken_heart, ":broken_heart:", ":broken_heart:"),
    GITHUB68(BrowType.E, R.mipmap.heartbeat, ":heartbeat:", ":heartbeat:"),
    GITHUB69(BrowType.E, R.mipmap.heartpulse, ":heartpulse:", ":heartpulse:"),
    GITHUB70(BrowType.E, R.mipmap.two_hearts, ":two_hearts:", ":two_hearts:"),
    GITHUB71(BrowType.E, R.mipmap.revolving_hearts, ":revolving_hearts:", ":revolving_hearts:"),
    GITHUB72(BrowType.E, R.mipmap.cupid, ":cupid:", ":cupid:"),
    GITHUB73(BrowType.E, R.mipmap.sparkling_heart, ":sparkling_heart:", ":sparkling_heart:"),
    GITHUB74(BrowType.E, R.mipmap.sparkles, ":sparkles:", ":sparkles:"),
    GITHUB75(BrowType.E, R.mipmap.star, ":star:", ":star:"),
    GITHUB76(BrowType.E, R.mipmap.star2, ":star2:", ":star2:"),
    GITHUB77(BrowType.E, R.mipmap.dizzy, ":dizzy:", ":dizzy:"),
    GITHUB78(BrowType.E, R.mipmap.boom, ":boom:", ":boom:"),
    GITHUB79(BrowType.E, R.mipmap.collision, ":collision:", ":collision:"),
    GITHUB80(BrowType.E, R.mipmap.anger, ":anger:", ":anger:"),
    GITHUB81(BrowType.E, R.mipmap.exclamation, ":exclamation:", ":exclamation:"),
    GITHUB82(BrowType.E, R.mipmap.question, ":question:", ":question:"),
    GITHUB83(BrowType.E, R.mipmap.grey_exclamation, ":grey_exclamation:", ":grey_exclamation:"),
    GITHUB84(BrowType.E, R.mipmap.grey_question, ":grey_question:", ":grey_question:"),
    GITHUB85(BrowType.E, R.mipmap.zzz, ":zzz:", ":zzz:"),
    GITHUB86(BrowType.E, R.mipmap.dash, ":dash:", ":dash:"),
    GITHUB87(BrowType.E, R.mipmap.sweat_drops, ":sweat_drops:", ":sweat_drops:"),
    GITHUB88(BrowType.E, R.mipmap.notes, ":notes:", ":notes:"),
    GITHUB89(BrowType.E, R.mipmap.musical_note, ":musical_note:", ":musical_note:"),
    GITHUB90(BrowType.E, R.mipmap.fire, ":fire:", ":fire:"),
    GITHUB91(BrowType.E, R.mipmap.hankey, ":hankey:", ":hankey:"),
    GITHUB92(BrowType.E, R.mipmap.poop, ":poop:", ":poop:"),
    GITHUB93(BrowType.E, R.mipmap.shit, ":shit:", ":shit:"),
    GITHUB94(BrowType.E, R.mipmap.thumbsup, ":+1:", ":+1:"),
    GITHUB95(BrowType.E, R.mipmap.thumbsup, ":thumbsup:", ":thumbsup:"),
    GITHUB96(BrowType.E, R.mipmap.the_1, ":-1:", ":-1:"),
    GITHUB97(BrowType.E, R.mipmap.thumbsdown, ":thumbsdown:", ":thumbsdown:"),
    GITHUB98(BrowType.E, R.mipmap.ok_hand, ":ok_hand:", ":ok_hand:"),
    GITHUB99(BrowType.E, R.mipmap.punch, ":punch:", ":punch:"),
    GITHUB100(BrowType.E, R.mipmap.facepunch, ":facepunch:", ":facepunch:"),
    GITHUB101(BrowType.E, R.mipmap.fist, ":fist:", ":fist:"),
    GITHUB102(BrowType.E, R.mipmap.v, ":v:", ":v:"),
    GITHUB103(BrowType.E, R.mipmap.wave, ":wave:", ":wave:"),
    GITHUB104(BrowType.E, R.mipmap.hand, ":hand:", ":hand:"),
    GITHUB105(BrowType.E, R.mipmap.raised_hand, ":raised_hand:", ":raised_hand:"),
    GITHUB106(BrowType.E, R.mipmap.open_hands, ":open_hands:", ":open_hands:"),
    GITHUB107(BrowType.E, R.mipmap.point_up, ":point_up:", ":point_up:"),
    GITHUB108(BrowType.E, R.mipmap.point_down, ":point_down:", ":point_down:"),
    GITHUB109(BrowType.E, R.mipmap.point_left, ":point_left:", ":point_left:"),
    GITHUB110(BrowType.E, R.mipmap.point_right, ":point_right:", ":point_right:"),
    GITHUB111(BrowType.E, R.mipmap.raised_hands, ":raised_hands:", ":raised_hands:"),
    GITHUB112(BrowType.E, R.mipmap.pray, ":pray:", ":pray:"),
    GITHUB113(BrowType.E, R.mipmap.point_up_2, ":point_up_2:", ":point_up_2:"),
    GITHUB114(BrowType.E, R.mipmap.clap, ":clap:", ":clap:"),
    GITHUB115(BrowType.E, R.mipmap.muscle, ":muscle:", ":muscle:"),
    GITHUB116(BrowType.E, R.mipmap.metal, ":metal:", ":metal:"),
    GITHUB117(BrowType.E, R.mipmap.fu, ":fu:", ":fu:"),
    GITHUB118(BrowType.E, R.mipmap.walking, ":walking:", ":walking:"),
    GITHUB119(BrowType.E, R.mipmap.runner, ":runner:", ":runner:"),
    GITHUB120(BrowType.E, R.mipmap.running, ":running:", ":running:"),
    GITHUB121(BrowType.E, R.mipmap.couple, ":couple:", ":couple:"),
    GITHUB122(BrowType.E, R.mipmap.family, ":family:", ":family:"),
    GITHUB123(BrowType.E, R.mipmap.two_men_holding_hands, ":two_men_holding_hands:", ":two_men_holding_hands:"),
    GITHUB124(BrowType.E, R.mipmap.two_women_holding_hands, ":two_women_holding_hands:", ":two_women_holding_hands:"),
    GITHUB125(BrowType.E, R.mipmap.dancer, ":dancer:", ":dancer:"),
    GITHUB126(BrowType.E, R.mipmap.dancers, ":dancers:", ":dancers:"),
    GITHUB127(BrowType.E, R.mipmap.ok_woman, ":ok_woman:", ":ok_woman:"),
    GITHUB128(BrowType.E, R.mipmap.no_good, ":no_good:", ":no_good:"),
    GITHUB129(BrowType.E, R.mipmap.information_desk_person, ":information_desk_person:", ":information_desk_person:"),
    GITHUB130(BrowType.E, R.mipmap.raising_hand, ":raising_hand:", ":raising_hand:"),
    GITHUB131(BrowType.E, R.mipmap.bride_with_veil, ":bride_with_veil:", ":bride_with_veil:"),
    GITHUB132(BrowType.E, R.mipmap.person_with_pouting_face, ":person_with_pouting_face:", ":person_with_pouting_face:"),
    GITHUB133(BrowType.E, R.mipmap.person_frowning, ":person_frowning:", ":person_frowning:"),
    GITHUB134(BrowType.E, R.mipmap.bow, ":bow:", ":bow:"),
    GITHUB135(BrowType.E, R.mipmap.couplekiss, ":couplekiss:", ":couplekiss:"),
    GITHUB136(BrowType.E, R.mipmap.couple_with_heart, ":couple_with_heart:", ":couple_with_heart:"),
    GITHUB137(BrowType.E, R.mipmap.massage, ":massage:", ":massage:"),
    GITHUB138(BrowType.E, R.mipmap.haircut, ":haircut:", ":haircut:"),
    GITHUB139(BrowType.E, R.mipmap.nail_care, ":nail_care:", ":nail_care:"),
    GITHUB140(BrowType.E, R.mipmap.boy, ":boy:", ":boy:"),
    GITHUB141(BrowType.E, R.mipmap.girl, ":girl:", ":girl:"),
    GITHUB142(BrowType.E, R.mipmap.woman, ":woman:", ":woman:"),
    GITHUB143(BrowType.E, R.mipmap.man, ":man:", ":man:"),
    GITHUB144(BrowType.E, R.mipmap.baby, ":baby:", ":baby:"),
    GITHUB145(BrowType.E, R.mipmap.older_woman, ":older_woman:", ":older_woman:"),
    GITHUB146(BrowType.E, R.mipmap.older_man, ":older_man:", ":older_man:"),
    GITHUB147(BrowType.E, R.mipmap.person_with_blond_hair, ":person_with_blond_hair:", ":person_with_blond_hair:"),
    GITHUB148(BrowType.E, R.mipmap.man_with_gua_pi_mao, ":man_with_gua_pi_mao:", ":man_with_gua_pi_mao:"),
    GITHUB149(BrowType.E, R.mipmap.man_with_turban, ":man_with_turban:", ":man_with_turban:"),
    GITHUB150(BrowType.E, R.mipmap.construction_worker, ":construction_worker:", ":construction_worker:"),
    GITHUB151(BrowType.E, R.mipmap.cop, ":cop:", ":cop:"),
    GITHUB152(BrowType.E, R.mipmap.angel, ":angel:", ":angel:"),
    GITHUB153(BrowType.E, R.mipmap.princess, ":princess:", ":princess:"),
    GITHUB154(BrowType.E, R.mipmap.smiley_cat, ":smiley_cat:", ":smiley_cat:"),
    GITHUB155(BrowType.E, R.mipmap.smile_cat, ":smile_cat:", ":smile_cat:"),
    GITHUB156(BrowType.E, R.mipmap.heart_eyes_cat, ":heart_eyes_cat:", ":heart_eyes_cat:"),
    GITHUB157(BrowType.E, R.mipmap.kissing_cat, ":kissing_cat:", ":kissing_cat:"),
    GITHUB158(BrowType.E, R.mipmap.smirk_cat, ":smirk_cat:", ":smirk_cat:"),
    GITHUB159(BrowType.E, R.mipmap.scream_cat, ":scream_cat:", ":scream_cat:"),
    GITHUB160(BrowType.E, R.mipmap.crying_cat_face, ":crying_cat_face:", ":crying_cat_face:"),
    GITHUB161(BrowType.E, R.mipmap.joy_cat, ":joy_cat:", ":joy_cat:"),
    GITHUB162(BrowType.E, R.mipmap.pouting_cat, ":pouting_cat:", ":pouting_cat:"),
    GITHUB163(BrowType.E, R.mipmap.japanese_ogre, ":japanese_ogre:", ":japanese_ogre:"),
    GITHUB164(BrowType.E, R.mipmap.japanese_goblin, ":japanese_goblin:", ":japanese_goblin:"),
    GITHUB165(BrowType.E, R.mipmap.see_no_evil, ":see_no_evil:", ":see_no_evil:"),
    GITHUB166(BrowType.E, R.mipmap.hear_no_evil, ":hear_no_evil:", ":hear_no_evil:"),
    GITHUB167(BrowType.E, R.mipmap.speak_no_evil, ":speak_no_evil:", ":speak_no_evil:"),
    GITHUB168(BrowType.E, R.mipmap.guardsman, ":guardsman:", ":guardsman:"),
    GITHUB169(BrowType.E, R.mipmap.skull, ":skull:", ":skull:"),
    GITHUB170(BrowType.E, R.mipmap.feet, ":feet:", ":feet:"),
    GITHUB171(BrowType.E, R.mipmap.lips, ":lips:", ":lips:"),
    GITHUB172(BrowType.E, R.mipmap.kiss, ":kiss:", ":kiss:"),
    GITHUB173(BrowType.E, R.mipmap.droplet, ":droplet:", ":droplet:"),
    GITHUB174(BrowType.E, R.mipmap.ear, ":ear:", ":ear:"),
    GITHUB175(BrowType.E, R.mipmap.eyes, ":eyes:", ":eyes:"),
    GITHUB176(BrowType.E, R.mipmap.nose, ":nose:", ":nose:"),
    GITHUB177(BrowType.E, R.mipmap.tongue, ":tongue:", ":tongue:"),
    GITHUB178(BrowType.E, R.mipmap.love_letter, ":love_letter:", ":love_letter:"),
    GITHUB179(BrowType.E, R.mipmap.bust_in_silhouette, ":bust_in_silhouette:", ":bust_in_silhouette:"),
    GITHUB180(BrowType.E, R.mipmap.busts_in_silhouette, ":busts_in_silhouette:", ":busts_in_silhouette:"),
    GITHUB181(BrowType.E, R.mipmap.speech_balloon, ":speech_balloon:", ":speech_balloon:"),
    GITHUB182(BrowType.E, R.mipmap.thought_balloon, ":thought_balloon:", ":thought_balloon:"),
    GITHUB183(BrowType.E, R.mipmap.feelsgood, ":feelsgood:", ":feelsgood:"),
    GITHUB184(BrowType.E, R.mipmap.finnadie, ":finnadie:", ":finnadie:"),
    GITHUB185(BrowType.E, R.mipmap.goberserk, ":goberserk:", ":goberserk:"),
    GITHUB186(BrowType.E, R.mipmap.godmode, ":godmode:", ":godmode:"),
    GITHUB187(BrowType.E, R.mipmap.hurtrealbad, ":hurtrealbad:", ":hurtrealbad:"),
    GITHUB188(BrowType.E, R.mipmap.rage1, ":rage1:", ":rage1:"),
    GITHUB189(BrowType.E, R.mipmap.rage2, ":rage2:", ":rage2:"),
    GITHUB190(BrowType.E, R.mipmap.rage3, ":rage3:", ":rage3:"),
    GITHUB191(BrowType.E, R.mipmap.rage4, ":rage4:", ":rage4:"),
    GITHUB192(BrowType.E, R.mipmap.suspect, ":suspect:", ":suspect:"),
    GITHUB193(BrowType.E, R.mipmap.trollface, ":trollface:", ":trollface:"),

    Nature0(BrowType.Other, R.mipmap.sunny, ":sunny:", ":sunny:"),
    Nature1(BrowType.Other, R.mipmap.umbrella, ":umbrella:", ":umbrella:"),
    Nature2(BrowType.Other, R.mipmap.cloud, ":cloud:", ":cloud:"),
    Nature3(BrowType.Other, R.mipmap.snowflake, ":snowflake:", ":snowflake:"),
    Nature4(BrowType.Other, R.mipmap.snowman, ":snowman:", ":snowman:"),
    Nature5(BrowType.Other, R.mipmap.zap, ":zap:", ":zap:"),
    Nature6(BrowType.Other, R.mipmap.cyclone, ":cyclone:", ":cyclone:"),
    Nature7(BrowType.Other, R.mipmap.foggy, ":foggy:", ":foggy:"),
    Nature8(BrowType.Other, R.mipmap.ocean, ":ocean:", ":ocean:"),
    Nature9(BrowType.Other, R.mipmap.cat, ":cat:", ":cat:"),
    Nature10(BrowType.Other, R.mipmap.dog, ":dog:", ":dog:"),
    Nature11(BrowType.Other, R.mipmap.mouse, ":mouse:", ":mouse:"),
    Nature12(BrowType.Other, R.mipmap.hamster, ":hamster:", ":hamster:"),
    Nature13(BrowType.Other, R.mipmap.rabbit, ":rabbit:", ":rabbit:"),
    Nature14(BrowType.Other, R.mipmap.wolf, ":wolf:", ":wolf:"),
    Nature15(BrowType.Other, R.mipmap.frog, ":frog:", ":frog:"),
    Nature16(BrowType.Other, R.mipmap.tiger, ":tiger:", ":tiger:"),
    Nature17(BrowType.Other, R.mipmap.koala, ":koala:", ":koala:"),
    Nature18(BrowType.Other, R.mipmap.bear, ":bear:", ":bear:"),
    Nature19(BrowType.Other, R.mipmap.pig, ":pig:", ":pig:"),
    Nature20(BrowType.Other, R.mipmap.pig_nose, ":pig_nose:", ":pig_nose:"),
    Nature21(BrowType.Other, R.mipmap.cow, ":cow:", ":cow:"),
    Nature22(BrowType.Other, R.mipmap.boar, ":boar:", ":boar:"),
    Nature23(BrowType.Other, R.mipmap.monkey_face, ":monkey_face:", ":monkey_face:"),
    Nature24(BrowType.Other, R.mipmap.monkey, ":monkey:", ":monkey:"),
    Nature25(BrowType.Other, R.mipmap.horse, ":horse:", ":horse:"),
    Nature26(BrowType.Other, R.mipmap.racehorse, ":racehorse:", ":racehorse:"),
    Nature27(BrowType.Other, R.mipmap.camel, ":camel:", ":camel:"),
    Nature28(BrowType.Other, R.mipmap.sheep, ":sheep:", ":sheep:"),
    Nature29(BrowType.Other, R.mipmap.elephant, ":elephant:", ":elephant:"),
    Nature30(BrowType.Other, R.mipmap.panda_face, ":panda_face:", ":panda_face:"),
    Nature31(BrowType.Other, R.mipmap.snake, ":snake:", ":snake:"),
    Nature32(BrowType.Other, R.mipmap.bird, ":bird:", ":bird:"),
    Nature33(BrowType.Other, R.mipmap.baby_chick, ":baby_chick:", ":baby_chick:"),
    Nature34(BrowType.Other, R.mipmap.hatched_chick, ":hatched_chick:", ":hatched_chick:"),
    Nature35(BrowType.Other, R.mipmap.hatching_chick, ":hatching_chick:", ":hatching_chick:"),
    Nature36(BrowType.Other, R.mipmap.chicken, ":chicken:", ":chicken:"),
    Nature37(BrowType.Other, R.mipmap.penguin, ":penguin:", ":penguin:"),
    Nature38(BrowType.Other, R.mipmap.turtle, ":turtle:", ":turtle:"),
    Nature39(BrowType.Other, R.mipmap.bug, ":bug:", ":bug:"),
    Nature40(BrowType.Other, R.mipmap.honeybee, ":honeybee:", ":honeybee:"),
    Nature41(BrowType.Other, R.mipmap.ant, ":ant:", ":ant:"),
    Nature42(BrowType.Other, R.mipmap.beetle, ":beetle:", ":beetle:"),
    Nature43(BrowType.Other, R.mipmap.snail, ":snail:", ":snail:"),
    Nature44(BrowType.Other, R.mipmap.octopus, ":octopus:", ":octopus:"),
    Nature45(BrowType.Other, R.mipmap.tropical_fish, ":tropical_fish:", ":tropical_fish:"),
    Nature46(BrowType.Other, R.mipmap.fish, ":fish:", ":fish:"),
    Nature47(BrowType.Other, R.mipmap.whale, ":whale:", ":whale:"),
    Nature48(BrowType.Other, R.mipmap.whale2, ":whale2:", ":whale2:"),
    Nature49(BrowType.Other, R.mipmap.dolphin, ":dolphin:", ":dolphin:"),
    Nature50(BrowType.Other, R.mipmap.cow2, ":cow2:", ":cow2:"),
    Nature51(BrowType.Other, R.mipmap.ram, ":ram:", ":ram:"),
    Nature52(BrowType.Other, R.mipmap.rat, ":rat:", ":rat:"),
    Nature53(BrowType.Other, R.mipmap.water_buffalo, ":water_buffalo:", ":water_buffalo:"),
    Nature54(BrowType.Other, R.mipmap.tiger2, ":tiger2:", ":tiger2:"),
    Nature55(BrowType.Other, R.mipmap.rabbit2, ":rabbit2:", ":rabbit2:"),
    Nature56(BrowType.Other, R.mipmap.dragon, ":dragon:", ":dragon:"),
    Nature57(BrowType.Other, R.mipmap.goat, ":goat:", ":goat:"),
    Nature58(BrowType.Other, R.mipmap.rooster, ":rooster:", ":rooster:"),
    Nature59(BrowType.Other, R.mipmap.dog2, ":dog2:", ":dog2:"),
    Nature60(BrowType.Other, R.mipmap.pig2, ":pig2:", ":pig2:"),
    Nature61(BrowType.Other, R.mipmap.mouse2, ":mouse2:", ":mouse2:"),
    Nature62(BrowType.Other, R.mipmap.ox, ":ox:", ":ox:"),
    Nature63(BrowType.Other, R.mipmap.dragon_face, ":dragon_face:", ":dragon_face:"),
    Nature64(BrowType.Other, R.mipmap.blowfish, ":blowfish:", ":blowfish:"),
    Nature65(BrowType.Other, R.mipmap.crocodile, ":crocodile:", ":crocodile:"),
    Nature66(BrowType.Other, R.mipmap.dromedary_camel, ":dromedary_camel:", ":dromedary_camel:"),
    Nature67(BrowType.Other, R.mipmap.leopard, ":leopard:", ":leopard:"),
    Nature68(BrowType.Other, R.mipmap.cat2, ":cat2:", ":cat2:"),
    Nature69(BrowType.Other, R.mipmap.poodle, ":poodle:", ":poodle:"),
    Nature70(BrowType.Other, R.mipmap.paw_prints, ":paw_prints:", ":paw_prints:"),
    Nature71(BrowType.Other, R.mipmap.bouquet, ":bouquet:", ":bouquet:"),
    Nature72(BrowType.Other, R.mipmap.cherry_blossom, ":cherry_blossom:", ":cherry_blossom:"),
    Nature73(BrowType.Other, R.mipmap.tulip, ":tulip:", ":tulip:"),
    Nature74(BrowType.Other, R.mipmap.four_leaf_clover, ":four_leaf_clover:", ":four_leaf_clover:"),
    Nature75(BrowType.Other, R.mipmap.rose, ":rose:", ":rose:"),
    Nature76(BrowType.Other, R.mipmap.sunflower, ":sunflower:", ":sunflower:"),
    Nature77(BrowType.Other, R.mipmap.hibiscus, ":hibiscus:", ":hibiscus:"),
    Nature78(BrowType.Other, R.mipmap.maple_leaf, ":maple_leaf:", ":maple_leaf:"),
    Nature79(BrowType.Other, R.mipmap.leaves, ":leaves:", ":leaves:"),
    Nature80(BrowType.Other, R.mipmap.fallen_leaf, ":fallen_leaf:", ":fallen_leaf:"),
    Nature81(BrowType.Other, R.mipmap.herb, ":herb:", ":herb:"),
    Nature82(BrowType.Other, R.mipmap.mushroom, ":mushroom:", ":mushroom:"),
    Nature83(BrowType.Other, R.mipmap.cactus, ":cactus:", ":cactus:"),
    Nature84(BrowType.Other, R.mipmap.palm_tree, ":palm_tree:", ":palm_tree:"),
    Nature85(BrowType.Other, R.mipmap.evergreen_tree, ":evergreen_tree:", ":evergreen_tree:"),
    Nature86(BrowType.Other, R.mipmap.deciduous_tree, ":deciduous_tree:", ":deciduous_tree:"),
    Nature87(BrowType.Other, R.mipmap.chestnut, ":chestnut:", ":chestnut:"),
    Nature88(BrowType.Other, R.mipmap.seedling, ":seedling:", ":seedling:"),
    Nature89(BrowType.Other, R.mipmap.blossom, ":blossom:", ":blossom:"),
    Nature90(BrowType.Other, R.mipmap.ear_of_rice, ":ear_of_rice:", ":ear_of_rice:"),
    Nature91(BrowType.Other, R.mipmap.shell, ":shell:", ":shell:"),
    Nature92(BrowType.Other, R.mipmap.globe_with_meridians, ":globe_with_meridians:", ":globe_with_meridians:"),
    Nature93(BrowType.Other, R.mipmap.sun_with_face, ":sun_with_face:", ":sun_with_face:"),
    Nature94(BrowType.Other, R.mipmap.full_moon_with_face, ":full_moon_with_face:", ":full_moon_with_face:"),
    Nature95(BrowType.Other, R.mipmap.new_moon_with_face, ":new_moon_with_face:", ":new_moon_with_face:"),
    Nature96(BrowType.Other, R.mipmap.new_moon, ":new_moon:", ":new_moon:"),
    Nature97(BrowType.Other, R.mipmap.waxing_crescent_moon, ":waxing_crescent_moon:", ":waxing_crescent_moon:"),
    Nature98(BrowType.Other, R.mipmap.first_quarter_moon, ":first_quarter_moon:", ":first_quarter_moon:"),
    Nature99(BrowType.Other, R.mipmap.waxing_gibbous_moon, ":waxing_gibbous_moon:", ":waxing_gibbous_moon:"),
    Nature100(BrowType.Other, R.mipmap.full_moon, ":full_moon:", ":full_moon:"),
    Nature101(BrowType.Other, R.mipmap.waning_gibbous_moon, ":waning_gibbous_moon:", ":waning_gibbous_moon:"),
    Nature102(BrowType.Other, R.mipmap.last_quarter_moon, ":last_quarter_moon:", ":last_quarter_moon:"),
    Nature103(BrowType.Other, R.mipmap.waning_crescent_moon, ":waning_crescent_moon:", ":waning_crescent_moon:"),
    Nature104(BrowType.Other, R.mipmap.last_quarter_moon_with_face, ":last_quarter_moon_with_face:", ":last_quarter_moon_with_face:"),
    Nature105(BrowType.Other, R.mipmap.first_quarter_moon_with_face, ":first_quarter_moon_with_face:", ":first_quarter_moon_with_face:"),
    Nature106(BrowType.Other, R.mipmap.moon, ":moon:", ":moon:"),
    Nature107(BrowType.Other, R.mipmap.earth_africa, ":earth_africa:", ":earth_africa:"),
    Nature108(BrowType.Other, R.mipmap.earth_americas, ":earth_americas:", ":earth_americas:"),
    Nature109(BrowType.Other, R.mipmap.earth_asia, ":earth_asia:", ":earth_asia:"),
    Nature110(BrowType.Other, R.mipmap.volcano, ":volcano:", ":volcano:"),
    Nature111(BrowType.Other, R.mipmap.milky_way, ":milky_way:", ":milky_way:"),
    Nature112(BrowType.Other, R.mipmap.partly_sunny, ":partly_sunny:", ":partly_sunny:"),
    Nature113(BrowType.Other, R.mipmap.octocat, ":octocat:", ":octocat:"),
    Nature114(BrowType.Other, R.mipmap.squirrel, ":squirrel:", ":squirrel:");

    private final BrowType type; //图片类别
    private final int resId; //图片资源
    private final String browTagStr; // emoji在互联网传递的字符串
    private final String remote;
    private static List<BrowEntity> list;
    private static Map<String, Integer> browMap;

    BrowRules(BrowType type, int id, String name, String remote) {
        this.type = type;
        this.resId = id;
        this.browTagStr = name;
        this.remote = remote;
    }

    BrowType getType() {
        return type;
    }

    int getResId() {
        return resId;
    }

    String getRemote() {
        return remote;
    }

    String getBrowTagStr() {
        return browTagStr;
    }

    public static BrowEntity getBrowEntity(BrowRules data) {
        return new BrowEntity(data.getType(), data.getResId(), data.getRemote(), data.getBrowTagStr());
    }

    public static List<BrowEntity> getAllBrow() {
        if (list != null) return list;
        list = new ArrayList<BrowEntity>();
        for (BrowRules data : values()) {
            list.add(getBrowEntity(data));
        }
        return list;
    }

    public static int getBrow(String browTagStr) {
        if (browMap == null) {
            browMap = new android.support.v4.util.ArrayMap();
            for (BrowRules data : values()) {
                browMap.put(data.getBrowTagStr(), data.getResId());
            }
        }
        int ret = browMap.get(browTagStr) == null ? 0 : browMap.get(browTagStr);//没有对应表情的字符串原样输出
        return ret;
    }

    public static void clear() {
        list = null;
        browMap = null;
    }
}